apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ep21sdz3t-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ep21sdz3t-java-quarkus-gitops